version: '3.7'

services:
  db:
    build: db
    restart: always
    ports:
      #  HOST : CONTAINER
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=alerts"
    volumes:
      - "./data/db:/var/lib/mysql"
